### PR TITLE
Replace System.Drawing with SixLabors.ImageSharp

### LINKED ISSUE #3: System.Drawing removed on all operating systems except Windows
When trying to run `Program.Main` on Linux with `net6.0` I get an exception.

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'GUI' threw an exception.
 ---> System.PlatformNotSupportedException: System.Drawing is not supported on this platform.
   at System.Drawing.Bitmap..ctor(String filename)
   at Graphics.LoadBitmap(String filename) in /home/ahouts/Projects/MarkovJunior/source/Graphics.cs:line 12
   at GUI..cctor() in /home/ahouts/Projects/MarkovJunior/source/GUI.cs:line 29
   --- End of inner exception stack trace ---
   at GUI.Draw(String name, Branch root, Branch current, Int32[] bitmap, Int32 WIDTH, Int32 HEIGHT, Dictionary`2 palette)
   at Program.Main() in /home/ahouts/Projects/MarkovJunior/source/Program.cs:line 67
```

Unfortunately Microsoft has decided to remove `System.Drawing` on all operating systems except Windows.
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

### PR DESCRIPTION
**Pull request by ahouts**
Microsoft recommends switching to a third party library for cross platform image manipulation:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

I implemented the Save/Load bitmap functions with `SixLabors.ImageSharp`, all examples seem to work on my system now.

closes #3 

Feel free to close this if you want to take a different approach, I was mostly interested in getting it to work on my system.

### CODE REVIEW

**Comment by alexdmiller** [comment]
I am still seeing this error on macOS:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'GUI' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GUI..cctor() in /Users/alex/projects/MarkovJunior-2/source/GUI.cs:line 30
   --- End of inner exception stack trace ---
   at GUI.Draw(String name, Branch root, Branch current, Int32[] bitmap, Int32 WIDTH, Int32 HEIGHT, Dictionary`2 palette)
   at Program.Main() in /Users/alex/projects/MarkovJunior-2/source/Program.cs:line 67
```

**Comment by ersinesen** [comment]
> 
You should clone the correct branch:
```git clone --branch replace-System.Drawing-with-SixLabors.ImageSharp https://github.com/ahouts/MarkovJunior.git```

And check the branch:
```git branch -a```

File: source/Graphics.cs [hunk 1]
```diff
@@ -1,35 +1,59 @@
...
+    
+    static UInt32 ReverseBytes(UInt32 value)
+    {
+        return (value & 0x000000FFU) << 24 | (value & 0x0000FF00U) << 8 |
+               (value & 0x00FF0000U) >> 8 | (value & 0xFF000000U) >> 24;
+    }
+
+    static UInt32 LeReverseBytes(UInt32 value)
+    {
+        return BitConverter.IsLittleEndian ? ReverseBytes(value) : value;
```
[the remark this answers is not in the document]
Comment (ahouts) [reply source/Graphics.cs]: Figured something like this existed, but I couldn't find it immediately. Thanks for the tip!

**Comment by ajzaff** [comment]
Works great on Debian Linux. Thanks for writing it.

File: source/Graphics.cs [hunk 2]
```diff
@@ -1,35 +1,51 @@
...
+            var result = new int[width * height];
+            for (var j = 0; j < height; j += 1)
+            {
+                for (var i = 0; i < width; i += 1)
+                {
+                    result[j * width + i] = unchecked((int) image[i, j].Bgra);
+                }
+            }
+
+            image.Dispose();
```
Comment (Sergio0694) [inline source/Graphics.cs:26]: You can use a `using` to avoid the explicit call to `Dispose`.
But most importantly, you can vectorize all this with the built-in API to copy the pixel buffer:
```suggestion
            using var image = Image.Load<Bgra32>(filename);

            int width = image.Width;
            int height = image.Height;
            int[] result = new int[width * height];

            image.CopyPixelDataTo(MemoryMarshal.Cast<int, Bgra32>(result));
```

File: source/Graphics.cs [hunk 3]
```diff
@@ -1,35 +1,51 @@
...
+        {
+            formattedData[i] = new Bgra32
+            {
+                Bgra = unchecked((uint) data[i])
+            };
+        }
+
+        var image = Image.WrapMemory(Configuration.Default, new Memory<Bgra32>(formattedData), width, height);
+        image.SaveAsPng(filename);
+        image.Dispose();
```
Comment (Sergio0694) [inline source/Graphics.cs:48]: You can use a `using` and skip the whole allocation + copy by wrapping the source directly:
```suggestion
        fixed (int* pData = data)
        {
            using var image = Image.WrapMemory<Bgra32>(pData, width, height);

            image.SaveAsPng(filename);
        }
```
A couple notes:
- Need to add `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` to the .csproj for this
- Make sure to **add width/height validation** as well before this suggested code.

**Review by Sergio0694 — CHANGES_REQUESTED** [review]
Love ImageSharp being used! 😄
I've left with some performance/memory improvements that can be done though.

**Comment by ahouts** [comment]
> Love ImageSharp being used! smile I've left with some performance/memory improvements that can be done though.

Doesn't seem likely this PR will be merged given @mxgmn's response on #3 and here: https://github.com/mxgmn/MarkovJunior/issues/9#issuecomment-1145817678. TBH I can appreciate the zero dependency approach @mxgmn seems to be going for given the only dependency this project had has caused issues.

I'll leave this PR open though so in the interim it has visibility until the permanent solution is implemented.

File: source/Graphics.cs (hunk 3 above)
Comment (JimBobSquarePants) [reply source/Graphics.cs:48]: Strongly recommend that this advice is followed. @Sergio0694 helped a lot to design and optimize the ImageSharp APIs

Comment (mxgmn) [reply source/Graphics.cs:48]: Thanks @Sergio0694 and @JimBobSquarePants, I updated it!
